"""
GitHub logger: Automatically updates STRATEGY_DOC.md via GitHub API.
Commits directly to main branch after each resolved trade, spike event, and daily summary.
"""

import base64
import hashlib
import logging
from datetime import datetime
from typing import Any

import aiohttp
import aiosqlite

import config
import database

logger = logging.getLogger("logger")


class StrategyDocLogger:
    """
    Maintains the STRATEGY_DOC.md file on GitHub as a living strategy log.
    Updates after:
    - Every resolved trade
    - Every volume spike event (traded or not)
    - At least once every 24 hours (summary update)
    """

    def __init__(self, db: aiosqlite.Connection) -> None:
        self._db = db
        self._session: aiohttp.ClientSession | None = None
        self._last_update: datetime | None = None
        self._current_sha: str | None = None  # Git blob SHA for update

    async def start(self) -> None:
        """Initialize HTTP session for GitHub API."""
        self._session = aiohttp.ClientSession(
            headers={
                "Authorization": f"token {config.GITHUB_TOKEN}",
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "polymarket-trading-agent",
            },
            timeout=aiohttp.ClientTimeout(total=30),
        )
        # Fetch current SHA of STRATEGY_DOC.md
        await self._fetch_current_sha()
        logger.info("Strategy doc logger started")

    async def stop(self) -> None:
        """Clean shutdown."""
        if self._session:
            await self._session.close()
        logger.info("Strategy doc logger stopped")

    # ── Public Interface ────────────────────────────────────────────────────

    async def log_trade_resolved(
        self, position: dict[str, Any]
    ) -> None:
        """Update STRATEGY_DOC.md after a trade resolves."""
        await self._update_doc(f"Trade resolved: {position.get('market_question', 'unknown')}")

    async def log_spike_event(
        self, event: dict[str, Any]
    ) -> None:
        """Update STRATEGY_DOC.md after a spike event."""
        await self._update_doc(f"Spike event: {event.get('market_id', 'unknown')[:12]}")

    async def log_daily_summary(self) -> None:
        """Periodic summary update."""
        await self._update_doc("Daily summary update")

    async def should_update_daily(self) -> bool:
        """Check if a daily summary update is due."""
        if self._last_update is None:
            return True
        elapsed = (datetime.utcnow() - self._last_update).total_seconds()
        return elapsed >= config.STRATEGY_DOC_UPDATE_INTERVAL_SEC

    # ── Document Generation ─────────────────────────────────────────────────

    async def _generate_document(self) -> str:
        """Generate the full STRATEGY_DOC.md content from database."""
        stats = await database.get_strategy_stats(self._db)
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        doc_parts: list[str] = []

        # Header
        doc_parts.append("# Polymarket Trading Agent — Strategy Log\n")
        doc_parts.append(f"> Auto-generated by the trading agent. Last updated: {now}\n")

        # Summary stats
        doc_parts.append("## Summary Stats\n")
        doc_parts.append(f"| Metric | Value |")
        doc_parts.append(f"|--------|-------|")
        doc_parts.append(f"| Total Trades | {stats['total_trades']} |")
        doc_parts.append(f"| Win Rate | {stats['win_rate']}% |")
        doc_parts.append(f"| Total P&L | ${stats['total_pnl']:,.2f} |")
        doc_parts.append(f"| Last Updated | {now} |")
        doc_parts.append("")

        # Copy trade performance
        doc_parts.append("## Copy Trade Performance\n")
        if stats["copy_stats"]:
            doc_parts.append("| Wallet | Trades Copied | Win Rate | P&L |")
            doc_parts.append("|--------|--------------|----------|-----|")
            for cs in stats["copy_stats"]:
                wallet = cs["source_wallet"][:12] + "..." if cs["source_wallet"] else "unknown"
                trades = cs["trades"]
                wins = cs["wins"]
                wr = f"{wins/trades*100:.0f}%" if trades > 0 else "N/A"
                pnl = cs["pnl"]
                doc_parts.append(f"| `{wallet}` | {trades} | {wr} | ${pnl:,.2f} |")
        else:
            doc_parts.append("*No copy trades resolved yet.*")
        doc_parts.append("")

        # Volume spike learnings
        doc_parts.append("## Volume Spike Learnings\n")
        if stats["recent_spikes"]:
            for spike in stats["recent_spikes"]:
                ts = spike.get("detected_at", "unknown")
                market = spike.get("market_slug", spike.get("market_id", "?"))[:30]
                outcome = spike.get("outcome", "?")
                mag = spike.get("spike_magnitude", 0)
                decision = spike.get("trade_decision", "?")
                rationale = spike.get("rationale", "")
                wall = "Yes" if spike.get("price_wall") else "No"
                trend = "Yes" if spike.get("trend_aligned") else "No"

                doc_parts.append(f"### {ts[:16]} — {market} ({outcome})")
                doc_parts.append(f"- **Magnitude:** {mag:.1f}x rolling average")
                doc_parts.append(f"- **Price wall:** {wall}")
                doc_parts.append(f"- **Trend aligned:** {trend}")
                doc_parts.append(f"- **Decision:** {decision}")
                doc_parts.append(f"- **Rationale:** {rationale}")

                if spike.get("outcome_correct") is not None:
                    correct = "Correct" if spike["outcome_correct"] else "Incorrect"
                    move = spike.get("price_move", 0)
                    doc_parts.append(f"- **Result:** {correct} (price moved {move:+.2f})")

                doc_parts.append("")
        else:
            doc_parts.append("*No spike events recorded yet.*")
        doc_parts.append("")

        # Observations section
        doc_parts.append("## Observations & Adaptations\n")
        doc_parts.append(await self._generate_observations(stats))
        doc_parts.append("")

        # Open positions
        open_positions = await database.get_open_positions(self._db)
        if open_positions:
            doc_parts.append("## Current Open Positions\n")
            doc_parts.append("| Market | Outcome | Strategy | Entry Price | Size | Opened |")
            doc_parts.append("|--------|---------|----------|-------------|------|--------|")
            for pos in open_positions:
                q = (pos.get("market_question", "") or "")[:40]
                doc_parts.append(
                    f"| {q} | {pos['outcome']} | {pos['strategy']} | "
                    f"${pos['entry_price']:.4f} | {pos['size']:.2f} | "
                    f"{pos['opened_at'][:16]} |"
                )
            doc_parts.append("")

        return "\n".join(doc_parts)

    async def _generate_observations(self, stats: dict[str, Any]) -> str:
        """Generate the free-form observations section based on data patterns."""
        observations: list[str] = []

        total = stats["total_trades"]
        if total == 0:
            return "*Agent is collecting data. Observations will appear after the first trades resolve.*"

        # Win rate observation
        wr = stats["win_rate"]
        if wr >= 60:
            observations.append(
                f"- Overall win rate of {wr}% is strong. Current strategy mix is working."
            )
        elif wr >= 45:
            observations.append(
                f"- Win rate of {wr}% is moderate. Watching for patterns in losses."
            )
        else:
            observations.append(
                f"- Win rate of {wr}% is below target. Need to tighten entry criteria."
            )

        # Copy trade observations
        if stats["copy_stats"]:
            best = stats["copy_stats"][0]
            if best["pnl"] > 0:
                observations.append(
                    f"- Best copied wallet (`{best['source_wallet'][:12]}...`) "
                    f"generating ${best['pnl']:.2f} P&L across {best['trades']} trades."
                )

            # Check for consistently losing wallets
            losers = [c for c in stats["copy_stats"] if c["pnl"] < 0]
            if losers:
                observations.append(
                    f"- {len(losers)} copied wallet(s) are net negative. "
                    f"Consider dropping lowest performers on next leaderboard refresh."
                )

        # Spike observations
        spikes = stats["recent_spikes"]
        if spikes:
            entered = [s for s in spikes if s["trade_decision"] == "enter"]
            faded = [s for s in spikes if s["trade_decision"] == "fade"]
            skipped = [s for s in spikes if s["trade_decision"] == "skip"]
            observations.append(
                f"- Recent spike breakdown: {len(entered)} entered, "
                f"{len(faded)} faded, {len(skipped)} skipped."
            )

            # Check if wall detection is predictive
            wall_spikes = [s for s in spikes if s.get("price_wall")]
            if wall_spikes:
                correct = sum(
                    1 for s in wall_spikes
                    if s.get("outcome_correct")
                )
                total_resolved = sum(
                    1 for s in wall_spikes
                    if s.get("outcome_correct") is not None
                )
                if total_resolved > 0:
                    wall_acc = correct / total_resolved * 100
                    observations.append(
                        f"- Price wall accuracy: {wall_acc:.0f}% "
                        f"({correct}/{total_resolved} correct predictions)."
                    )

        if not observations:
            observations.append(
                "- Collecting more data to identify patterns. "
                "Will update observations as trades resolve."
            )

        return "\n".join(observations)

    # ── GitHub API ──────────────────────────────────────────────────────────

    async def _fetch_current_sha(self) -> None:
        """Get the current SHA of STRATEGY_DOC.md in the repo."""
        if not config.GITHUB_TOKEN or not config.GITHUB_OWNER:
            logger.warning("GitHub credentials not configured, logging to local only")
            return

        url = (
            f"https://api.github.com/repos/{config.GITHUB_OWNER}/"
            f"{config.GITHUB_REPO}/contents/{config.STRATEGY_DOC_PATH}"
            f"?ref={config.GITHUB_BRANCH}"
        )

        try:
            assert self._session is not None
            async with self._session.get(url) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    self._current_sha = data.get("sha")
                    logger.debug("Current STRATEGY_DOC.md SHA: %s", self._current_sha)
                elif resp.status == 404:
                    logger.info("STRATEGY_DOC.md does not exist yet, will create")
                    self._current_sha = None
                else:
                    logger.warning("GitHub API returned %d", resp.status)
        except Exception as e:
            logger.error("Failed to fetch STRATEGY_DOC.md SHA: %s", e)

    async def _update_doc(self, commit_message: str) -> None:
        """Generate and push updated STRATEGY_DOC.md to GitHub."""
        content = await self._generate_document()

        # Check if content actually changed
        content_hash = hashlib.sha256(content.encode()).hexdigest()
        rows = await self._db.execute_fetchall(
            "SELECT content_hash FROM doc_updates ORDER BY id DESC LIMIT 1"
        )
        if rows and rows[0]["content_hash"] == content_hash:
            logger.debug("STRATEGY_DOC.md unchanged, skipping update")
            return

        # Write locally first
        try:
            with open(config.STRATEGY_DOC_PATH, "w") as f:
                f.write(content)
            logger.info("Updated local STRATEGY_DOC.md")
        except Exception as e:
            logger.error("Failed to write local STRATEGY_DOC.md: %s", e)

        # Push to GitHub if configured
        if config.GITHUB_TOKEN and config.GITHUB_OWNER:
            await self._push_to_github(content, commit_message)

        # Log the update
        await self._db.execute(
            """INSERT INTO doc_updates (updated_at, update_type, content_hash)
               VALUES (?, ?, ?)""",
            (datetime.utcnow().isoformat(), commit_message, content_hash),
        )
        await self._db.commit()
        self._last_update = datetime.utcnow()

    async def _push_to_github(
        self, content: str, commit_message: str
    ) -> None:
        """Commit STRATEGY_DOC.md to GitHub via the Contents API."""
        url = (
            f"https://api.github.com/repos/{config.GITHUB_OWNER}/"
            f"{config.GITHUB_REPO}/contents/{config.STRATEGY_DOC_PATH}"
        )

        encoded_content = base64.b64encode(content.encode()).decode()

        payload: dict[str, Any] = {
            "message": f"[agent] {commit_message}",
            "content": encoded_content,
            "branch": config.GITHUB_BRANCH,
        }

        if self._current_sha:
            payload["sha"] = self._current_sha

        try:
            assert self._session is not None
            async with self._session.put(url, json=payload) as resp:
                if resp.status in (200, 201):
                    data = await resp.json()
                    self._current_sha = data.get("content", {}).get("sha")
                    logger.info(
                        "Pushed STRATEGY_DOC.md to GitHub: %s",
                        commit_message,
                    )
                else:
                    body = await resp.text()
                    logger.error(
                        "GitHub push failed (%d): %s", resp.status, body[:200],
                    )
                    # Refresh SHA in case of conflict
                    await self._fetch_current_sha()
        except Exception as e:
            logger.error("GitHub push error: %s", e)
