"""
GitHub logger: Automatically updates STRATEGY_DOC.md via GitHub API.
Commits directly to main branch after each resolved trade, spike event, and daily summary.
"""

import base64
import hashlib
import logging
from datetime import datetime
from typing import Any

import aiohttp
import aiosqlite

import config
import database

logger = logging.getLogger("logger")


class StrategyDocLogger:
    """
    Maintains the STRATEGY_DOC.md file on GitHub as a living strategy log.
    Updates after:
    - Every resolved trade
    - Every volume spike event (traded or not)
    - At least once every 24 hours (summary update)
    """

    def __init__(self, db: aiosqlite.Connection) -> None:
        self._db = db
        self._session: aiohttp.ClientSession | None = None
        self._last_update: datetime | None = None
        self._current_sha: str | None = None  # Git blob SHA for update

    async def start(self) -> None:
        """Initialize HTTP session for GitHub API."""
        self._session = aiohttp.ClientSession(
            headers={
                "Authorization": f"token {config.GITHUB_TOKEN}",
                "Accept": "application/vnd.github.v3+json",
                "User-Agent": "polymarket-trading-agent",
            },
            timeout=aiohttp.ClientTimeout(total=30),
        )
        # Fetch current SHA of STRATEGY_DOC.md
        await self._fetch_current_sha()
        logger.info("Strategy doc logger started")

    async def stop(self) -> None:
        """Clean shutdown."""
        if self._session:
            await self._session.close()
        logger.info("Strategy doc logger stopped")

    # ── Public Interface ────────────────────────────────────────────────────

    async def log_trade_resolved(
        self, position: dict[str, Any]
    ) -> None:
        """Update STRATEGY_DOC.md after a trade resolves."""
        await self._update_doc(f"Trade resolved: {position.get('market_question', 'unknown')}")

    async def log_spike_event(
        self, event: dict[str, Any]
    ) -> None:
        """Update STRATEGY_DOC.md after a spike event."""
        await self._update_doc(f"Spike event: {event.get('market_id', 'unknown')[:12]}")

    async def log_daily_summary(self) -> None:
        """Periodic summary update."""
        await self._update_doc("Daily summary update")

    async def should_update_daily(self) -> bool:
        """Check if a daily summary update is due."""
        if self._last_update is None:
            return True
        elapsed = (datetime.utcnow() - self._last_update).total_seconds()
        return elapsed >= config.STRATEGY_DOC_UPDATE_INTERVAL_SEC

    # ── Document Generation ─────────────────────────────────────────────────

    async def _generate_document(self) -> str:
        """Generate the full STRATEGY_DOC.md content from database."""
        stats = await database.get_strategy_stats(self._db)
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        doc_parts: list[str] = []

        # Header
        doc_parts.append("# Polymarket Trading Agent — Strategy Log\n")
        doc_parts.append(f"> Auto-generated by the trading agent. Last updated: {now}\n")

        # Summary stats
        doc_parts.append("## Summary Stats\n")
        doc_parts.append(f"| Metric | Value |")
        doc_parts.append(f"|--------|-------|")
        doc_parts.append(f"| Total Trades | {stats['total_trades']} |")
        doc_parts.append(f"| Win Rate | {stats['win_rate']}% |")
        doc_parts.append(f"| Total P&L | ${stats['total_pnl']:,.2f} |")
        doc_parts.append(f"| Last Updated | {now} |")
        doc_parts.append("")

        # Copy trade performance
        doc_parts.append("## Copy Trade Performance\n")

        open_totals = stats.get("open_totals", {})
        open_cnt = open_totals.get("cnt", 0)
        unique_markets = open_totals.get("unique_markets", 0)
        total_cost = open_totals.get("total_cost", 0.0)

        if open_cnt > 0:
            doc_parts.append(
                f"**{open_cnt} open position(s)** across {unique_markets} market(s) "
                f"· total cost basis ${total_cost:,.2f}\n"
            )

        if stats["copy_stats"]:
            doc_parts.append("### Resolved Trades by Wallet")
            doc_parts.append("| Wallet | Trades | Win Rate | P&L |")
            doc_parts.append("|--------|--------|----------|-----|")
            for cs in stats["copy_stats"]:
                wallet = cs["source_wallet"][:12] + "..." if cs["source_wallet"] else "unknown"
                trades = cs["trades"]
                wins = cs["wins"]
                wr = f"{wins/trades*100:.0f}%" if trades > 0 else "N/A"
                pnl = cs["pnl"]
                doc_parts.append(f"| `{wallet}` | {trades} | {wr} | ${pnl:,.2f} |")
            doc_parts.append("")

        if stats.get("open_by_wallet"):
            doc_parts.append("### Open Positions by Source Wallet")
            doc_parts.append("| Wallet | Open Trades | Cost Basis | First Opened |")
            doc_parts.append("|--------|-------------|------------|--------------|")
            for row in stats["open_by_wallet"]:
                wallet = (row["source_wallet"] or "unknown")[:16] + "..."
                doc_parts.append(
                    f"| `{wallet}` | {row['open_count']} | "
                    f"${row['cost_basis']:,.2f} | {row['first_opened'][:16]} |"
                )
            doc_parts.append("")

        if not stats["copy_stats"] and not stats.get("open_by_wallet"):
            doc_parts.append("*No copy trades recorded yet.*")
            doc_parts.append("")

        # Volume spike learnings
        doc_parts.append("## Volume Spike Learnings\n")
        if stats["recent_spikes"]:
            for spike in stats["recent_spikes"]:
                ts = spike.get("detected_at", "unknown")
                market = spike.get("market_slug", spike.get("market_id", "?"))[:30]
                outcome = spike.get("outcome", "?")
                mag = spike.get("spike_magnitude", 0)
                decision = spike.get("trade_decision", "?")
                rationale = spike.get("rationale", "")
                wall = "Yes" if spike.get("price_wall") else "No"
                trend = "Yes" if spike.get("trend_aligned") else "No"

                doc_parts.append(f"### {ts[:16]} — {market} ({outcome})")
                doc_parts.append(f"- **Magnitude:** {mag:.1f}x rolling average")
                doc_parts.append(f"- **Price wall:** {wall}")
                doc_parts.append(f"- **Trend aligned:** {trend}")
                doc_parts.append(f"- **Decision:** {decision}")
                doc_parts.append(f"- **Rationale:** {rationale}")

                if spike.get("outcome_correct") is not None:
                    correct = "Correct" if spike["outcome_correct"] else "Incorrect"
                    move = spike.get("price_move", 0)
                    doc_parts.append(f"- **Result:** {correct} (price moved {move:+.2f})")

                doc_parts.append("")
        else:
            doc_parts.append("*No spike events recorded yet.*")
        doc_parts.append("")

        # Observations section
        doc_parts.append("## Observations & Adaptations\n")
        doc_parts.append(await self._generate_observations(stats))
        doc_parts.append("")

        # Market regime analytics section — populates once trades are tagged
        regime_stats = stats.get("regime_stats", [])
        if regime_stats:
            doc_parts.append("## Market Regime Analytics\n")
            doc_parts.append(
                "> Regime is tagged at trade entry using recent spike activity and "
                "historical win rate. The bot auto-disables volume-spike entries when "
                "`choppy` or `risk_off` regime win rate drops below 45%.\n"
            )
            doc_parts.append("| Regime | Trades | Win Rate | Total P&L |")
            doc_parts.append("|--------|--------|----------|-----------|")
            for row in regime_stats:
                regime = row.get("market_regime", "?")
                trades = row.get("trades", 0)
                win_rate = row.get("win_rate", 0)
                total_pnl = row.get("total_pnl", 0)
                doc_parts.append(
                    f"| {regime} | {trades} | {win_rate}% | ${total_pnl:,.2f} |"
                )
            doc_parts.append("")

            # Regime SQL query for manual analysis
            doc_parts.append("<details><summary>SQL: regime breakdown query</summary>\n")
            doc_parts.append("```sql")
            doc_parts.append("SELECT market_regime,")
            doc_parts.append("       COUNT(*) AS trades,")
            doc_parts.append("       ROUND(AVG(CASE WHEN pnl > 0 THEN 1.0 ELSE 0.0 END) * 100, 1) AS win_rate,")
            doc_parts.append("       ROUND(SUM(pnl), 2) AS total_pnl")
            doc_parts.append("FROM positions")
            doc_parts.append("GROUP BY market_regime")
            doc_parts.append("ORDER BY total_pnl DESC;")
            doc_parts.append("```\n")
            doc_parts.append("</details>\n")
        elif stats["total_trades"] >= 10:
            doc_parts.append("## Market Regime Analytics\n")
            doc_parts.append(
                "*Regime tagging active. Trades will appear here once positions close.*\n"
            )

        # Open positions
        open_positions = await database.get_open_positions(self._db)
        if open_positions:
            doc_parts.append("## Current Open Positions\n")
            doc_parts.append("| Market | Outcome | Strategy | Entry Price | Size | Opened |")
            doc_parts.append("|--------|---------|----------|-------------|------|--------|")
            for pos in open_positions:
                q = (pos.get("market_question", "") or "")[:40]
                doc_parts.append(
                    f"| {q} | {pos['outcome']} | {pos['strategy']} | "
                    f"${pos['entry_price']:.4f} | {pos['size']:.2f} | "
                    f"{pos['opened_at'][:16]} |"
                )
            doc_parts.append("")

        return "\n".join(doc_parts)

    async def _generate_observations(self, stats: dict[str, Any]) -> str:
        """Generate the free-form observations section based on data patterns."""
        parts: list[str] = []

        # ── User field observations (from dashboard) ─────────────────────────
        try:
            user_obs = await self._db.execute_fetchall(
                "SELECT created_at, source, market_tag, text "
                "FROM observations ORDER BY created_at DESC LIMIT 50"
            )
        except Exception:
            user_obs = []

        if user_obs:
            parts.append("### Field Observations\n")
            for row in user_obs:
                ts = row["created_at"][:16].replace("T", " ") + " UTC"
                src = row["source"] or "manual"
                tag = f" · #{row['market_tag']}" if row.get("market_tag") else ""
                parts.append(f"**{ts}** · {src}{tag}")
                parts.append(f"> {row['text']}\n")
            parts.append("")

        # ── Agent auto-generated analysis ────────────────────────────────────
        observations: list[str] = []

        total = stats["total_trades"]
        open_totals = stats.get("open_totals", {})
        open_cnt = int(open_totals.get("cnt", 0))
        unique_markets = int(open_totals.get("unique_markets", 0))
        total_cost = float(open_totals.get("total_cost", 0.0))
        order_summary = stats.get("order_summary", {})

        # Active operations summary (useful even before trades resolve)
        if open_cnt > 0:
            observations.append(
                f"- Agent has {open_cnt} open position(s) across {unique_markets} unique "
                f"market(s) with ${total_cost:,.2f} total cost basis. "
                f"Awaiting resolution to calculate win rate and P&L."
            )

        # Order execution health
        failed = order_summary.get("failed", 0)
        filled = order_summary.get("filled", 0) + order_summary.get("pending", 0)
        if failed > 0 and filled == 0:
            observations.append(
                f"- **Geo-block active:** {failed} order attempt(s) blocked by Polymarket "
                f"region restriction (HTTP 403). Agent must run from a supported region "
                f"(e.g. deploy on Railway US region) to execute live trades."
            )
        elif failed > 0:
            fail_rate = failed / (failed + filled) * 100
            observations.append(
                f"- Order failure rate: {fail_rate:.0f}% ({failed} failed, {filled} filled/pending). "
                f"Monitor for region or API key issues."
            )

        # Copy trade source wallet diversity
        open_by_wallet = stats.get("open_by_wallet", [])
        if open_by_wallet:
            wallet_count = len(open_by_wallet)
            top_wallet = open_by_wallet[0]
            top_name = (top_wallet["source_wallet"] or "unknown")[:16]
            observations.append(
                f"- Positions sourced from {wallet_count} tracked wallet(s). "
                f"Largest contributor: `{top_name}...` "
                f"({top_wallet['open_count']} trade(s), ${top_wallet['cost_basis']:,.2f} cost basis)."
            )

        # Resolved trade win rate (once data exists)
        if total > 0:
            wr = stats["win_rate"]
            if wr >= 60:
                observations.append(
                    f"- Win rate {wr}% across {total} resolved trade(s) — strategy performing well."
                )
            elif wr >= 45:
                observations.append(
                    f"- Win rate {wr}% across {total} resolved trade(s) — moderate. Watching loss patterns."
                )
            else:
                observations.append(
                    f"- Win rate {wr}% across {total} resolved trade(s) — below target. "
                    f"Tightening entry criteria."
                )

        # Copy trade wallet P&L (resolved)
        if stats["copy_stats"]:
            best = stats["copy_stats"][0]
            if best["pnl"] > 0:
                observations.append(
                    f"- Best resolved wallet (`{best['source_wallet'][:12]}...`) "
                    f"generating ${best['pnl']:.2f} P&L across {best['trades']} trade(s)."
                )
            losers = [c for c in stats["copy_stats"] if c["pnl"] < 0]
            if losers:
                observations.append(
                    f"- {len(losers)} wallet(s) net negative on resolved trades. "
                    f"Will drop lowest performers on next leaderboard refresh."
                )

        # Spike observations
        spikes = stats["recent_spikes"]
        if spikes:
            entered = [s for s in spikes if s["trade_decision"] == "enter"]
            faded = [s for s in spikes if s["trade_decision"] == "fade"]
            skipped = [s for s in spikes if s["trade_decision"] == "skip"]
            observations.append(
                f"- Volume spike breakdown: {len(entered)} entered, "
                f"{len(faded)} faded, {len(skipped)} skipped."
            )
            wall_spikes = [s for s in spikes if s.get("price_wall")]
            if wall_spikes:
                correct = sum(1 for s in wall_spikes if s.get("outcome_correct"))
                resolved_wall = sum(
                    1 for s in wall_spikes if s.get("outcome_correct") is not None
                )
                if resolved_wall > 0:
                    observations.append(
                        f"- Price wall accuracy: {correct/resolved_wall*100:.0f}% "
                        f"({correct}/{resolved_wall} correct)."
                    )

        if not observations and not user_obs:
            observations.append(
                "- Agent is running. Observations will populate as positions open and resolve."
            )

        if observations:
            if parts:
                parts.append("### Agent Analysis\n")
            parts.extend(observations)

        return "\n".join(parts)

    # ── GitHub API ──────────────────────────────────────────────────────────

    async def _fetch_current_sha(self) -> None:
        """Get the current SHA of STRATEGY_DOC.md in the repo."""
        if not config.GITHUB_TOKEN or not config.GITHUB_OWNER:
            logger.warning("GitHub credentials not configured, logging to local only")
            return

        url = (
            f"https://api.github.com/repos/{config.GITHUB_OWNER}/"
            f"{config.GITHUB_REPO}/contents/{config.STRATEGY_DOC_PATH}"
            f"?ref={config.GITHUB_BRANCH}"
        )

        try:
            assert self._session is not None
            async with self._session.get(url) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    self._current_sha = data.get("sha")
                    logger.debug("Current STRATEGY_DOC.md SHA: %s", self._current_sha)
                elif resp.status == 404:
                    logger.info("STRATEGY_DOC.md does not exist yet, will create")
                    self._current_sha = None
                else:
                    logger.warning("GitHub API returned %d", resp.status)
        except Exception as e:
            logger.error("Failed to fetch STRATEGY_DOC.md SHA: %s", e)

    async def _update_doc(self, commit_message: str) -> None:
        """Generate and push updated STRATEGY_DOC.md to GitHub."""
        content = await self._generate_document()

        # Check if content actually changed
        content_hash = hashlib.sha256(content.encode()).hexdigest()
        rows = await self._db.execute_fetchall(
            "SELECT content_hash FROM doc_updates ORDER BY id DESC LIMIT 1"
        )
        if rows and rows[0]["content_hash"] == content_hash:
            logger.debug("STRATEGY_DOC.md unchanged, skipping update")
            return

        # Write locally first
        try:
            with open(config.STRATEGY_DOC_PATH, "w") as f:
                f.write(content)
            logger.info("Updated local STRATEGY_DOC.md")
        except Exception as e:
            logger.error("Failed to write local STRATEGY_DOC.md: %s", e)

        # Push to GitHub if configured
        if config.GITHUB_TOKEN and config.GITHUB_OWNER:
            await self._push_to_github(content, commit_message)

        # Log the update
        await self._db.execute(
            """INSERT INTO doc_updates (updated_at, update_type, content_hash)
               VALUES (?, ?, ?)""",
            (datetime.utcnow().isoformat(), commit_message, content_hash),
        )
        await self._db.commit()
        self._last_update = datetime.utcnow()

    async def _push_to_github(
        self, content: str, commit_message: str
    ) -> None:
        """Commit STRATEGY_DOC.md to GitHub via the Contents API."""
        url = (
            f"https://api.github.com/repos/{config.GITHUB_OWNER}/"
            f"{config.GITHUB_REPO}/contents/{config.STRATEGY_DOC_PATH}"
        )

        encoded_content = base64.b64encode(content.encode()).decode()

        payload: dict[str, Any] = {
            "message": f"[agent] {commit_message}",
            "content": encoded_content,
            "branch": config.GITHUB_BRANCH,
        }

        if self._current_sha:
            payload["sha"] = self._current_sha

        try:
            assert self._session is not None
            async with self._session.put(url, json=payload) as resp:
                if resp.status in (200, 201):
                    data = await resp.json()
                    self._current_sha = data.get("content", {}).get("sha")
                    logger.info(
                        "Pushed STRATEGY_DOC.md to GitHub: %s",
                        commit_message,
                    )
                else:
                    body = await resp.text()
                    logger.error(
                        "GitHub push failed (%d): %s", resp.status, body[:200],
                    )
                    # Refresh SHA in case of conflict
                    await self._fetch_current_sha()
        except Exception as e:
            logger.error("GitHub push error: %s", e)
